# Generated by Django 3.0.5 on 2020-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0003_auto_20200604_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
