# Generated by Django 3.0.5 on 2020-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0004_auto_20200604_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
