# Generated by Django 3.0.5 on 2020-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0012_article_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='img_url',
            field=models.TextField(blank=True, default='https://img4.itbox.ua/200x200/prod_img/4/U0373294_big.jpg', null=True),
        ),
    ]
